import { Grant } from './types';

export const mockGrants: Grant[] = [
  // ==================== GOVERNMENT AGENCIES ====================
  {
    id: '1',
    organizationName: 'National Endowment for the Arts - Grants for Arts Projects',
    website: 'https://www.arts.gov',
    budgetMin: 10000,
    budgetMax: 100000,
    deadline: '2026-02-12',
    deadlineNotes: 'Two cycles per year: February 12, 2026 and July 9, 2026. Part 1 (Intent to Apply) due first, then Part 2 via Applicant Portal.',
    location: 'Washington, DC',
    artsDiscipline: 'General Arts',
    fundingType: 'Project-Based',
    funderType: 'Government',
    eligibility: 'US-based 501(c)(3) nonprofit organizations with at least 5 years of arts programming history. Units of state/local government and federally recognized tribal communities also eligible.',
    overview: 'NEA Grants for Arts Projects supports public engagement with, and access to, excellent art across the nation. Requires 1:1 cost share match. Supports disciplines including Music, Musical Theater, Opera, Presenting, Dance, Theater, and Visual Arts.',
    contactEmail: 'webmgr@arts.gov',
    applicationUrl: 'https://www.arts.gov/grants/grants-for-arts-projects',
    isActive: true
  },
  {
    id: '2',
    organizationName: 'DC Commission on the Arts and Humanities',
    website: 'https://dcarts.dc.gov',
    budgetMin: 5000,
    budgetMax: 75000,
    deadline: '2026-04-22',
    deadlineNotes: 'General Operating Support (GOS) deadline typically in April. Multiple grant programs available throughout the year.',
    location: 'Washington, DC',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Government',
    eligibility: 'DC-based arts organizations with 501(c)(3) status and at least 2 years of programming. Must have principal place of business in DC.',
    overview: 'CAH provides grants to arts organizations that contribute to the cultural vitality of Washington, DC. Programs include General Operating Support, Capital Projects, and various project grants. Multi-year funding available.',
    contactEmail: 'cah@dc.gov',
    applicationUrl: 'https://dcarts.dc.gov/service/cah-grants',
    isActive: true
  },
  {
    id: '3',
    organizationName: 'Virginia Commission for the Arts',
    website: 'https://vca.virginia.gov',
    budgetMin: 2500,
    budgetMax: 25000,
    deadline: '2026-02-01',
    deadlineNotes: 'Short Form due February 1; Long Form due March 1. For small organizations (budgets $20K-$150K), fixed grants of $2,500.',
    location: 'Richmond, VA',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Government',
    eligibility: 'Virginia-based 501(c)(3) nonprofit arts organizations with at least 2 years of programming history. New applicants must contact the Commission before applying.',
    overview: 'VCA General Operating Support is the largest program offered by the Virginia Commission for the Arts. Awards made annually; organizations must reapply each year.',
    contactEmail: 'arts@virginia.gov',
    applicationUrl: 'https://vca.virginia.gov/grants/',
    isActive: true
  },
  {
    id: '4',
    organizationName: 'Maryland State Arts Council',
    website: 'https://msac.org',
    budgetMin: 2500,
    budgetMax: 84000,
    deadline: '2026-01-17',
    deadlineNotes: 'Multiple programs with different deadlines. Arts in Education: rolling July-January. Creativity Grants: rolling July-March.',
    location: 'Baltimore, MD',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Government',
    eligibility: 'Maryland-incorporated 501(c)(3) nonprofit organizations in operation for one year or more. Units of local government and colleges/universities also eligible.',
    overview: 'MSAC supports Maryland arts organizations through operating grants, project grants, and artist fellowships. Arts in Education grants up to $84,000 for Teaching Artist Organizations. FY2026 runs July 1, 2025 to June 30, 2026.',
    contactEmail: 'msac@maryland.gov',
    applicationUrl: 'https://msac.org/programs/grants-organizations',
    isActive: true
  },
  {
    id: '5',
    organizationName: 'New York State Council on the Arts (NYSCA)',
    website: 'https://arts.ny.gov',
    budgetMin: 10000,
    budgetMax: 100000,
    deadline: '2026-06-26',
    deadlineNotes: 'FY2027 deadline expected June 2026. Organizations must be prequalified in NYS Grants Gateway to apply.',
    location: 'New York, NY',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Government',
    eligibility: 'Nonprofit organizations incorporated or registered in New York State with principal place of business in NY. Must be prequalified in the NYS Grants Gateway.',
    overview: 'NYSCA provides funding to nonprofit arts organizations throughout New York State. Support for Artists grants are $10,000 through fiscal sponsors. Prequalification required before applying.',
    contactEmail: 'info@arts.ny.gov',
    applicationUrl: 'https://arts.ny.gov/nysca-grant-opportunities',
    isActive: true
  },
  {
    id: '6',
    organizationName: 'California Arts Council',
    website: 'https://arts.ca.gov',
    budgetMin: 5000,
    budgetMax: 50000,
    deadline: '2026-06-05',
    deadlineNotes: 'Impact Projects and Arts and Youth typically due in June. Cultural Districts program has different timeline.',
    location: 'Sacramento, CA',
    artsDiscipline: 'General Arts',
    fundingType: 'Project-Based',
    funderType: 'Government',
    eligibility: 'California-based nonprofit arts/cultural organizations, arts-based units of local government, or nonprofit social service organizations with ongoing arts programming. Minimum 2-year history required.',
    overview: 'CAC supports arts organizations across California with operating support and project grants. Impact Projects support collaborative work centering artists in community issues. Focus on equity, access, and community strengthening.',
    contactEmail: 'info@arts.ca.gov',
    applicationUrl: 'https://arts.ca.gov/grants/',
    isActive: true
  },
  {
    id: '7',
    organizationName: 'Pennsylvania Council on the Arts',
    website: 'https://www.arts.pa.gov',
    budgetMin: 2500,
    budgetMax: 35000,
    deadline: '2026-05-15',
    location: 'Harrisburg, PA',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Government',
    eligibility: 'Pennsylvania-based nonprofit arts organizations with established programming.',
    overview: 'PCA provides operating and project support to Pennsylvania arts organizations. Grants strengthen organizational capacity and expand access to arts experiences.',
    contactEmail: 'ra-arts@pa.gov',
    applicationUrl: 'https://www.arts.pa.gov/grants',
    isActive: true
  },

  // ==================== REGIONAL ARTS ORGANIZATIONS ====================
  {
    id: '8',
    organizationName: 'Mid Atlantic Arts - USArtists International',
    website: 'https://www.midatlanticarts.org',
    budgetMin: 1000,
    budgetMax: 11000,
    deadline: '2026-02-25',
    deadlineNotes: 'One deadline this year: February 25, 2026 by 11:59 PM Eastern. Letters of invitation due March 4, 2026.',
    location: 'Baltimore, MD',
    artsDiscipline: 'Performing Arts',
    fundingType: 'Project-Based',
    funderType: 'Service Organization',
    eligibility: 'US-based performing artists and ensembles with confirmed invitations to perform at international festivals or presenting arts markets. Individuals and groups from all states/territories eligible.',
    overview: 'USArtists International supports in-person performances by US artists at international festivals and presenting markets. Grants up to $11,000 with 1:1 match required. Supports all performing arts disciplines.',
    contactEmail: 'info@midatlanticarts.org',
    applicationUrl: 'https://www.midatlanticarts.org/opportunity/usartists-international/',
    isActive: true
  },
  {
    id: '9',
    organizationName: 'New England Foundation for the Arts (NEFA) - NEST',
    website: 'https://www.nefa.org',
    budgetMin: 500,
    budgetMax: 5000,
    deadline: '2026-04-01',
    deadlineNotes: 'Two deadlines in FY26: December 1, 2025 and April 1, 2026. Grants cover up to 60% of artist fee.',
    location: 'Boston, MA',
    artsDiscipline: 'Performing Arts',
    fundingType: 'Project-Based',
    funderType: 'Service Organization',
    eligibility: 'New England-based presenters booking New England-based touring artists. Nonprofit status required.',
    overview: 'New England States Touring (NEST) grants support touring and presenting of performing arts throughout New England. Grants range $500-$5,000 covering up to 60% of artist fee. Note: National Dance Project and National Theater Project are sunsetting.',
    contactEmail: 'info@nefa.org',
    applicationUrl: 'https://www.nefa.org/NEST',
    isActive: true
  },
  {
    id: '10',
    organizationName: 'South Arts - Arts in Community',
    website: 'https://www.southarts.org',
    budgetMin: 3000,
    budgetMax: 10000,
    deadline: '2026-09-03',
    deadlineNotes: 'Applications open July 2026. Requires 3-day minimum residency with at least 3 public activities.',
    location: 'Atlanta, GA',
    artsDiscipline: 'Performing Arts',
    fundingType: 'Project-Based',
    funderType: 'Service Organization',
    eligibility: 'Arts organizations in AL, FL, GA, KY, LA, MS, NC, SC, and TN. Artist must travel from one Southern state to another. Organizations cannot have received South Arts presentation grant in previous 2 years.',
    overview: 'Arts in Community Grants support organizations bringing artists from one Southern state to communities in another Southern state. Requires minimum 3-day residency with at least 4 hours of artist engagement across 3 public activities.',
    contactEmail: 'info@southarts.org',
    applicationUrl: 'https://www.southarts.org/grants-opportunities/arts-community-grants',
    isActive: true
  },

  // ==================== MUSIC SERVICE ORGANIZATIONS ====================
  {
    id: '11',
    organizationName: 'Chamber Music America - Classical Commissioning',
    website: 'https://www.chamber-music.org',
    budgetMin: 4125,
    budgetMax: 20000,
    deadline: '2026-09-25',
    deadlineNotes: 'Artistic Projects deadline typically late September. Classical Commissioning redesigned due to NEA funding changes.',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Commissioning',
    funderType: 'Service Organization',
    eligibility: 'Professional chamber music ensembles with US-based nonprofit status performing together for at least 2 years. Operating budgets under $250,000 for Artistic Projects.',
    overview: 'CMA Classical Commissioning supports creation of new chamber music works. Artistic Projects grants $7,500-$20,000 for small ensembles and presenters in NYC. New Jazz Works deadline February 2026.',
    contactEmail: 'grants@chamber-music.org',
    applicationUrl: 'https://chambermusicamerica.org/grants/',
    isActive: true
  },
  {
    id: '12',
    organizationName: 'New Music USA - Creator Fund',
    website: 'https://www.newmusicusa.org',
    budgetMin: 3000,
    budgetMax: 10000,
    deadline: '2025-11-21',
    deadlineNotes: 'November 2025 cycle for Northeast/Mid-Atlantic, Midwest, and NY artists. November 2026 for West, South, and NY. Organization Fund deadline typically March.',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Project-Based',
    funderType: 'Service Organization',
    eligibility: 'Individual music creators with minimum 3 years professional experience. Must be US-based, not enrolled in degree programs. Regional eligibility rotates annually.',
    overview: 'Creator Fund supports individual composers creating new works. Average grant $3,000, up to $5,000. Organization Fund offers up to $10,000 for nonprofits. Thea Musgrave Performer-Composer Collaboration Grant: $10,000.',
    contactEmail: 'grants@newmusicusa.org',
    applicationUrl: 'https://newmusicusa.org/program/new-music-creator-fund/',
    isActive: true
  },
  {
    id: '13',
    organizationName: 'OPERA America - Opera Grants for Women Composers',
    website: 'https://www.operaamerica.org',
    budgetMin: 5000,
    budgetMax: 15000,
    deadline: '2026-01-22',
    deadlineNotes: 'Discovery Grants: Intent to apply December 18, 2025; Application January 22, 2026. NYC Opera Grants have October deadline.',
    location: 'New York, NY',
    artsDiscipline: 'Performing Arts',
    fundingType: 'Commissioning',
    funderType: 'Service Organization',
    eligibility: 'Professional opera companies that are OPERA America members in good standing. Discovery Grants support workshops, readings, and development activities.',
    overview: 'OPERA America grants support creation of new American operas. Discovery Grants up to $15,000 for development activities. Commissioning Grants support full productions. Over $1 million awarded annually across 11 programs.',
    contactEmail: 'grants@operaamerica.org',
    applicationUrl: 'https://www.operaamerica.org/programs/services/grants-awards/',
    isActive: true
  },
  {
    id: '14',
    organizationName: 'Aaron Copland Fund for Music - Project Support',
    website: 'https://coplandfund.org',
    budgetMin: 1000,
    budgetMax: 20000,
    deadline: '2026-11-12',
    deadlineNotes: 'Performance Program ended in 2025. New Project Support Program deadline November 12, 2026 for September 2026-August 2027 activities.',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Project-Based',
    funderType: 'Private Foundation',
    eligibility: 'US-based performing ensembles, presenters, music service organizations, and record companies. Must support contemporary concert music and jazz by American composers.',
    overview: 'The Copland Fund supports performance and dissemination of contemporary American concert music and jazz. Performance Program ended 2025; Project Support Program continues. Account requests due by July 24, 2026.',
    contactEmail: 'info@coplandfund.org',
    applicationUrl: 'https://coplandfund.org/programs/project-support-program',
    isActive: true
  },
  {
    id: '15',
    organizationName: 'Amphion Foundation',
    website: 'https://amphionfoundation.org',
    budgetMin: 1500,
    budgetMax: 7500,
    deadline: '2026-02-26',
    deadlineNotes: 'Spring cycle: February 26, 2026. Fall cycle: mid-September 2026. Elliott Carter Special Grant: April 16, 2026.',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Project-Based',
    funderType: 'Private Foundation',
    eligibility: 'US-based 501(c)(3) organizations presenting contemporary concert music. Performing and presenting organizations and music service organizations eligible.',
    overview: 'Amphion Foundation supports performance and dissemination of contemporary concert music. Grants typically $1,500-$7,500; larger grants possible for significant projects. Awards notifications July (Spring) and January (Fall).',
    contactEmail: 'grantsmanager@amphionfoundation.org',
    applicationUrl: 'https://amphionfoundation.org/programs/amphion-grant-program',
    isActive: true
  },
  {
    id: '16',
    organizationName: 'Chorus America',
    website: 'https://chorusamerica.org',
    budgetMin: 5000,
    budgetMax: 50000,
    deadline: '2026-03-15',
    deadlineNotes: 'Dale Warland Singers Commission currently accepting applications. Music Education Partnership Grants in multi-year cycle, not currently open.',
    location: 'Washington, DC',
    artsDiscipline: 'Classical Music',
    fundingType: 'Project-Based',
    funderType: 'Service Organization',
    eligibility: 'US and Canadian-based choral music and community organizations. Music Education Partnership requires collaboration with schools serving K-12.',
    overview: 'Chorus America offers grants for US and Canadian-based choral organizations. Dale Warland Singers Commission funds new artistically meaningful works. Music Ed Partnership Grants provide up to $50,000 over two years.',
    contactEmail: 'service@chorusamerica.org',
    applicationUrl: 'https://chorusamerica.org/grants',
    isActive: true
  },
  {
    id: '17',
    organizationName: 'National Performance Network - Creation Fund',
    website: 'https://npnweb.org',
    budgetMin: 15000,
    budgetMax: 35000,
    deadline: '2026-05-18',
    deadlineNotes: 'Spring 2026 deadline: May 18, 2026 for projects premiering January 2027-December 2029. Development Fund has rolling deadline (60 days prior to activities).',
    location: 'New Orleans, LA',
    artsDiscipline: 'Performing Arts',
    fundingType: 'Commissioning',
    funderType: 'Service Organization',
    eligibility: 'Artists apply with team of at least two NPN National Partner co-commissioners. Each commissioner contributes $2,000-$3,000 cash match.',
    overview: 'NPN Creation Fund supports creation and touring of new performance work. Each artist receives minimum $15,000 (NPN matches commissioner contributions). Development Fund rolling deadline for work-in-progress.',
    contactEmail: 'info@npnweb.org',
    applicationUrl: 'https://npnweb.org/programs/cdf/',
    isActive: true
  },

  // ==================== MAJOR PRIVATE FOUNDATIONS ====================
  {
    id: '18',
    organizationName: 'The Andrew W. Mellon Foundation',
    website: 'https://mellon.org',
    budgetMin: 50000,
    budgetMax: 500000,
    deadline: '',
    deadlineNotes: 'By invitation only. Staff seek out organizations before inviting proposals. Letters of inquiry may be submitted but uninvited proposals not accepted.',
    location: 'New York, NY',
    artsDiscipline: 'Performing Arts',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'US-based 501(c)(3) charities and equivalent international organizations. No direct funding to individuals, K-12 education, or fundraising events.',
    overview: 'Mellon Foundation supports performing arts organizations demonstrating artistic excellence and innovation. Multi-year general operating grants available. Jazz Giants initiative: $35 million for jazz preservation. Invitation-only.',
    isInvitationOnly: true,
    isActive: true
  },
  {
    id: '19',
    organizationName: 'The Kresge Foundation - Arts & Culture',
    website: 'https://kresge.org',
    budgetMin: 5000,
    budgetMax: 5000000,
    deadline: '',
    deadlineNotes: 'Organizational grants by invitation. Detroit Artist Fellowships: $50,000 awards, deadline January 15, 2026.',
    location: 'Troy, MI',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'For Artist Fellowships: Metro Detroit artists (Wayne, Oakland, Macomb counties). Organizational grants by invitation for creative placemaking and cultural equity work.',
    overview: 'Kresge Arts & Culture invests in creative placemaking and community impact. Detroit Artist Fellowships: $50,000 (up from $40,000). Gilda Snowden Emerging Artist Awards: $5,000. $162.8M in annual grants overall.',
    isInvitationOnly: true,
    isActive: true
  },
  {
    id: '20',
    organizationName: 'Ford Foundation - Creativity and Free Expression',
    website: 'https://www.fordfoundation.org',
    budgetMin: 100000,
    budgetMax: 5600000,
    deadline: '',
    deadlineNotes: 'By invitation/relationship only. NYC Good Neighbor Committee applications open late summer/early fall.',
    location: 'New York, NY',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'Organizations using arts for social change. Substantial multi-year operating support for organizations staffed by and serving people of color, women, and disabled artists.',
    overview: 'Ford Foundation Creativity and Free Expression has provided $230 million to 500+ organizations since 2018. Median grant: $200,000. Does not fund advocacy projects, educational initiatives, or endowment funds. Invitation-only.',
    isInvitationOnly: true,
    isActive: true
  },
  {
    id: '21',
    organizationName: 'Barr Foundation - Arts & Creativity',
    website: 'https://www.barrfoundation.org',
    budgetMin: 50000,
    budgetMax: 500000,
    deadline: '',
    deadlineNotes: 'Primarily invitation-based. Complete online inquiry form; allow 6 weeks for response.',
    location: 'Boston, MA',
    artsDiscipline: 'Performing Arts',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'Greater Boston area arts organizations. Does not fund individual artists, individual projects, or programs. Focus on long-term systems change.',
    overview: 'Barr Foundation awarded $130+ million in 2025. Cultural Evolution Initiative: $3.3 million to 8 organizations. Multi-year operating grants for long-term partnerships. Inquiry form available on website.',
    isInvitationOnly: true,
    isActive: true
  },

  // ==================== COMMISSIONING FOUNDATIONS ====================
  {
    id: '22',
    organizationName: 'Koussevitzky Music Foundation - Library of Congress',
    website: 'https://www.koussevitzky.org',
    budgetMin: 5000,
    budgetMax: 20000,
    deadline: '2026-01-15',
    deadlineNotes: 'Application deadline January 15, 2026. Results announced by August. Performance period begins September 2026.',
    location: 'Washington, DC',
    artsDiscipline: 'Classical Music',
    fundingType: 'Commissioning',
    funderType: 'Private Foundation',
    eligibility: 'Performing organizations from any country commissioning composers of any nationality. Must have record of excellence in contemporary music performance.',
    overview: 'Koussevitzky Foundation at the Library of Congress commissions new orchestral and chamber works. Up to $20,000 for symphonic works with 50% match required from submitting organization. Hundreds of works commissioned since founding.',
    contactEmail: 'KoussevitzkyFoundation@loc.gov',
    applicationUrl: 'https://www.koussevitzky.org/how-to-apply/',
    isActive: true
  },
  {
    id: '23',
    organizationName: 'Fromm Music Foundation at Harvard',
    website: 'https://frommfoundation.fas.harvard.edu',
    budgetMin: 12000,
    budgetMax: 16000,
    deadline: '2026-06-10',
    deadlineNotes: '2026 application opens April 2026. Commission amount $12,000 plus up to $4,000 for premiere performance. Results announced December.',
    location: 'Cambridge, MA',
    artsDiscipline: 'Classical Music',
    fundingType: 'Commissioning',
    funderType: 'Private Foundation',
    eligibility: 'Composers must be legal US permanent residents at time of application. All types of compositions eligible regardless of idiom, instrumentation, style, or use of technology.',
    overview: 'Fromm Commission: $12,000 ($6,000 advance at commissioning). Performing group may request up to $4,000 for premiere. Completed scores due within 3 years. 12 American composers selected annually.',
    contactEmail: 'fromm@fas.harvard.edu',
    applicationUrl: 'https://frommfoundation.fas.harvard.edu/fromm-music-foundation-commissions',
    isActive: true
  },
  {
    id: '24',
    organizationName: 'Barlow Endowment for Music Composition',
    website: 'https://barlow.byu.edu',
    budgetMin: 5000,
    budgetMax: 15000,
    deadline: '2026-06-01',
    deadlineNotes: 'Deadline June 1, 2026 by 11:59pm MDT. Decisions announced by August 31. 2026 Barlow Prize: $15,000 commission for two pianos and two percussionists.',
    location: 'Provo, UT',
    artsDiscipline: 'Classical Music',
    fundingType: 'Commissioning',
    funderType: 'Private Foundation',
    eligibility: 'Composers cannot be among premiering performers, conductors, or agents. No consecutive year awards for General/Latter-day Saints Commissions.',
    overview: 'Barlow Prize: $15,000 commission for major new work. General Commission requests up to $14,000. 2026 Prize for two pianos and two percussionists premiered by consortium including Yarn/Wire.',
    contactEmail: 'barlow@byu.edu',
    applicationUrl: 'https://barlow.byu.edu/barlow-prize',
    isActive: true
  },
  {
    id: '25',
    organizationName: 'Alice M. Ditson Fund at Columbia University',
    website: 'https://ditsonfund.org',
    budgetMin: 5000,
    budgetMax: 5000,
    deadline: '2026-11-15',
    deadlineNotes: 'Ditson Conductors Award nomination-based. Award presented annually to conductor championing American music.',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'Conductors demonstrating commitment to performance of American music. Nomination-based award established in 1945.',
    overview: 'Oldest award honoring conductors for commitment to American music. $5,000 prize plus citation from Columbia University. Past recipients include Leonard Bernstein, Marin Alsop, Alan Gilbert.',
    applicationUrl: 'https://ditsonfund.org/conductors-award',
    isActive: true
  },

  // ==================== FELLOWSHIP PROGRAMS ====================
  {
    id: '26',
    organizationName: 'Creative Capital Award',
    website: 'https://creative-capital.org',
    budgetMin: 10000,
    budgetMax: 50000,
    deadline: '2026-04-02',
    deadlineNotes: 'Application portal opens March 2, 2026; deadline April 2, 2026 at 3PM ET for 2027 awards.',
    location: 'New York, NY',
    artsDiscipline: 'General Arts',
    fundingType: 'Project-Based',
    funderType: 'Private Foundation',
    eligibility: 'Individual artists with at least 5 years professional practice. Cannot be enrolled in degree program or have previously received Creative Capital Award.',
    overview: 'Creative Capital Award provides up to $50,000 in unrestricted project grants plus career development services. State of the Art Prize: $10,000 to one artist per US state/territory. 2026 cycle awarded $2.9 million to 109 artists.',
    contactEmail: 'info@creative-capital.org',
    applicationUrl: 'https://creative-capital.org/creative-capital-award/award-application/',
    isActive: true
  },
  {
    id: '27',
    organizationName: 'United States Artists Fellowship',
    website: 'https://www.unitedstatesartists.org',
    budgetMin: 50000,
    budgetMax: 50000,
    deadline: '',
    deadlineNotes: 'Nomination-based program. Artists nominated by rotating panel of arts professionals, scholars, and curators.',
    location: 'Chicago, IL',
    artsDiscipline: 'General Arts',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'Established artists demonstrating artistic innovation and cultural contribution. 50 fellows selected annually across 9 disciplines. Nomination required.',
    overview: 'USA Fellowships: $50,000 unrestricted awards plus financial planning, career consulting, and personal care services. 2026 recipients represent 19 states. Berresford Prize: $50,000 to arts leader.',
    applicationUrl: 'https://www.unitedstatesartists.org/programs/usa-fellowship',
    isInvitationOnly: true,
    isActive: true
  },
  {
    id: '28',
    organizationName: 'Herb Alpert Award in the Arts',
    website: 'https://herbalpertawards.org',
    budgetMin: 75000,
    budgetMax: 75000,
    deadline: '',
    deadlineNotes: 'Nomination-based. Panels select risk-taking mid-career artists in dance, film/video, music, theatre, and visual arts.',
    location: 'Santa Monica, CA',
    artsDiscipline: 'General Arts',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'Mid-career artists challenging and transforming their disciplines. Nomination-based, administered by California Institute of the Arts.',
    overview: 'Herb Alpert Award: $75,000 unrestricted prize plus CalArts residency. 2026: 10 recipients (expanded from 5). Now in 30th year with 164 artists awarded to date.',
    applicationUrl: 'https://herbalpertawards.org/',
    isInvitationOnly: true,
    isActive: true
  },
  {
    id: '29',
    organizationName: 'Jerome Foundation - Jerome Hill Artist Fellowship',
    website: 'https://www.jeromefdn.org',
    budgetMin: 60000,
    budgetMax: 60000,
    deadline: '',
    deadlineNotes: 'Applications currently closed. Check website for next cycle opening. 3-year fellowship: $20,000 per year.',
    location: 'Saint Paul, MN',
    artsDiscipline: 'General Arts',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'Early career artists (2nd-10th year as generative artist) based in Minnesota or New York City. Multiple disciplines supported.',
    overview: 'Jerome Hill Artist Fellowship: $60,000 over 3 years ($20,000 annually) for flexible, self-designed creative plans. 45 Fellows selected for 2025-2028. Supports dance, film, literature, music, technology arts, theater.',
    contactEmail: 'info@jeromefdn.org',
    applicationUrl: 'https://www.jeromefdn.org/jerome-hill-artist-fellowship',
    isActive: true
  },
  {
    id: '30',
    organizationName: 'McKnight Foundation - Composer Fellowships',
    website: 'https://www.mcknight.org',
    budgetMin: 10000,
    budgetMax: 100000,
    deadline: '2025-12-17',
    deadlineNotes: 'Composer Fellowships deadline December 17, 2025 via American Composers Forum. Visual Artist Fellowships deadline March 20, 2026.',
    location: 'Minneapolis, MN',
    artsDiscipline: 'Classical Music',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'Minnesota-based artists with at least 1 year residency. Mid-career with sustained body of work. Cannot have received McKnight fellowship in same discipline within 5 years.',
    overview: 'McKnight Composer Fellowships: 4 awards via American Composers Forum. Visual Artist Fellowships: $25,000 stipend plus residency. Foundation contributes $2.8 million annually to statewide fellowships across 15 disciplines.',
    contactEmail: 'info@mcknight.org',
    applicationUrl: 'https://www.mcknight.org/programs/arts-culture/mcknight-artist-culture-bearer-fellowships/',
    isActive: true
  },
  {
    id: '31',
    organizationName: 'Sphinx Organization',
    website: 'https://www.sphinxmusic.org',
    budgetMin: 5000,
    budgetMax: 100000,
    deadline: '2025-10-20',
    deadlineNotes: 'SphinxConnect Fellowships opened July 22, 2025. Applicants must be 18+ by October 20, 2025. Competition: December annually.',
    location: 'Detroit, MI',
    artsDiscipline: 'Classical Music',
    fundingType: 'Fellowship',
    funderType: 'Service Organization',
    eligibility: 'Black and Latinx classical musicians age 18+. Sphinx Competition for junior (under 18) and senior (18-30) divisions.',
    overview: 'Sphinx transforms lives through diversity in classical music. Competition prizes total $100,000+. SphinxConnect convening January 22-24, 2026. Orchestral Futurist Fellowship combines administration, performance, and community engagement.',
    contactEmail: 'info@sphinxmusic.org',
    applicationUrl: 'https://www.sphinxmusic.org/fellowships',
    isActive: true
  },
  {
    id: '32',
    organizationName: 'YoungArts Foundation',
    website: 'https://www.youngarts.org',
    budgetMin: 250,
    budgetMax: 10000,
    deadline: '2025-10-08',
    deadlineNotes: '2026 application deadline: October 8, 2025 at 8 PM ET. Winners announced November 24. 2027 applications open summer 2026.',
    location: 'Miami, FL',
    artsDiscipline: 'Music Education',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'US citizens or permanent residents aged 15-18 or in grades 10-12. Demonstrate excellence in Classical Music, Dance, Design, Film, Jazz, Photography, Theater, Visual Arts, Voice, or Writing.',
    overview: 'YoungArts identifies exceptional young artists. Awards $250-$10,000 plus National YoungArts Week in Miami. Winners eligible for US Presidential Scholar in the Arts nomination.',
    contactEmail: 'apply@youngarts.org',
    applicationUrl: 'https://youngarts.org/apply/',
    isActive: true
  },
  {
    id: '33',
    organizationName: 'Concert Artists Guild',
    website: 'https://www.concertartists.org',
    budgetMin: 5000,
    budgetMax: 25000,
    deadline: '',
    deadlineNotes: 'Rolling applications year-round (new 2025 model). Screenings: NYC Sept 2025, Rochester Oct 2025, Chicago Nov 2025, LA Feb 2026. Awards Ceremony May 11, 2026.',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Fellowship',
    funderType: 'Service Organization',
    eligibility: 'Emerging classical musicians. New rolling selection model replaced annual competition for 75th anniversary in 2026.',
    overview: 'CAG shifted to year-round artist selection with reduced fees, live screenings, and active scouting. Winners receive North American management, NYC debut, and Citizen Musician Bootcamp. Grand Winners get international management with YCAT.',
    contactEmail: 'info@concertartists.org',
    applicationUrl: 'https://www.concertartists.org/join-our-roster-about',
    isActive: true
  },
  {
    id: '34',
    organizationName: 'American Piano Awards',
    website: 'https://pianoawards.org',
    budgetMin: 25000,
    budgetMax: 200000,
    deadline: '2026-02-15',
    deadlineNotes: 'Applications close February 15, 2026 for 2027 Jazz competition. Classical and Jazz alternate biennially.',
    location: 'Indianapolis, IN',
    artsDiscipline: 'Classical Music',
    fundingType: 'Fellowship',
    funderType: 'Service Organization',
    eligibility: 'American pianists. Nomination required from distinguished music professionals. 2027 competition is Jazz division.',
    overview: 'American Piano Awards (formerly American Pianists Association) alternates between Jazz and Classical competitions. All 5 finalists receive $25,000. Winner prize package valued at $200,000+. Finals Week April 2027.',
    contactEmail: 'info@pianoawards.org',
    applicationUrl: 'https://pianoawards.org',
    isActive: true
  },

  // ==================== SUMMER PROGRAMS/FESTIVALS ====================
  {
    id: '35',
    organizationName: 'Tanglewood Music Center',
    website: 'https://www.bso.org/tmc',
    budgetMin: 5000,
    budgetMax: 20000,
    deadline: '2026-01-22',
    deadlineNotes: 'Instrumental: January 22, 2026 (live) / February 3, 2026 (video). Conducting: November 4, 2025. BSO Resident Fellowship: March 3, 2026.',
    location: 'Lenox, MA',
    artsDiscipline: 'Music Education',
    fundingType: 'Fellowship',
    funderType: 'Service Organization',
    eligibility: 'Advanced musicians at least 18 years old who have completed most formal training. All tuition, housing, and meals provided at no charge.',
    overview: 'TMC is Boston Symphony Orchestra summer academy. 2026 session: June 19 - August 18. Full fellowships provided. Conducting Fellows work with Andris Nelsons. Instrumental Fellows perform with TMC Orchestra.',
    contactEmail: 'tmc@bso.org',
    applicationUrl: 'https://www.bso.org/tmc/apply-to-the-tmc',
    isActive: true
  },
  {
    id: '36',
    organizationName: 'Aspen Music Festival and School',
    website: 'https://www.aspenmusicfestival.com',
    budgetMin: 5000,
    budgetMax: 25000,
    deadline: '2025-09-15',
    deadlineNotes: 'Summer 2026 deadline: September 15, 2025 (most programs). Opera/VocalARTS: August 1, 2025. Nearly 85% receive financial assistance.',
    location: 'Aspen, CO',
    artsDiscipline: 'Music Education',
    fundingType: 'Fellowship',
    funderType: 'Service Organization',
    eligibility: 'Advanced students and emerging professionals. All applicants automatically considered for fellowship assistance.',
    overview: 'AMFS provides $3.8 million in financial assistance annually. 85% receive some assistance; majority receive full support. Fellowship covers tuition, room, board. Fleming Artist fellowships include $1,500 stipend.',
    contactEmail: 'studentservices@aspenmusic.org',
    applicationUrl: 'https://www.aspenmusicfestival.com/students-welcome/admissions/',
    isActive: true
  },
  {
    id: '37',
    organizationName: 'Bang on a Can Summer Music Festival',
    website: 'https://bangonacan.org',
    budgetMin: 500,
    budgetMax: 5000,
    deadline: '2026-01-14',
    deadlineNotes: 'Deadline January 14, 2026 at 5pm ET. $40 application fee (waivers available). Results by March 5. Deposit $500 due within 2 weeks of acceptance.',
    location: 'North Adams, MA',
    artsDiscipline: 'Classical Music',
    fundingType: 'Fellowship',
    funderType: 'Service Organization',
    eligibility: 'Innovative composers and performers at least 21 years old. Global applicants welcome. Participation fee: $3,750 tuition + $700 room/board.',
    overview: 'Three-week contemporary music program at MASS MoCA, July 13-August 2, 2026. Composer premieres during LOUD Weekend Festival. Daily rehearsals, seminars, world music workshops, technology sessions. Limited financial aid available.',
    contactEmail: 'info@bangonacan.org',
    applicationUrl: 'https://bangonacan.org/summer_festival/info_for_applicants/',
    isActive: true
  },

  // ==================== COMMUNITY FOUNDATIONS ====================
  {
    id: '38',
    organizationName: 'Greater Washington Community Foundation',
    website: 'https://www.thecommunityfoundation.org',
    budgetMin: 5000,
    budgetMax: 30000,
    deadline: '2025-09-15',
    deadlineNotes: 'Community Impact Fund deadline September 15, 2025 for 2-year grants up to $15,000/year. Quarterly grant rounds throughout year.',
    location: 'Washington, DC',
    artsDiscipline: 'General Arts',
    fundingType: 'General Operating',
    funderType: 'Community Foundation',
    eligibility: 'Organizations serving the greater Washington, DC metropolitan area. Arts Forward Fund focuses on BIPOC-led and BIPOC-serving organizations.',
    overview: 'GWCF supports arts and culture initiatives across DC region. Arts Forward Fund: $2.7 million to 130+ organizations (60% BIPOC-led/serving). Community Impact Fund: up to 10 two-year unrestricted grants.',
    contactEmail: 'bmurphy@thecommunityfoundation.org',
    applicationUrl: 'https://www.thecommunityfoundation.org/grant-opportunities',
    isActive: true
  },
  {
    id: '39',
    organizationName: 'HumanitiesDC',
    website: 'https://humanitiesdc.org',
    budgetMin: 2000,
    budgetMax: 25000,
    deadline: '2026-02-18',
    deadlineNotes: 'Cycle I grants deadline February 18, 2026. Cycle II (including General Operating Support) opens March 2026. Draft review requests due February 10, 2026.',
    location: 'Washington, DC',
    artsDiscipline: 'Humanities',
    fundingType: 'Project-Based',
    funderType: 'Community Foundation',
    eligibility: 'Organizations presenting humanities programming in Washington, DC. Visions grants for public interpretations of humanities scholarship.',
    overview: 'HumanitiesDC supports programs celebrating DC people, places, and stories. Visions grants up to $25,000. General Operating Support up to $25,000 for nonprofits under $2M budget. Oral history grants also available.',
    contactEmail: 'grants@humanitiesdc.org',
    applicationUrl: 'https://humanitiesdc.org/grant-opportunities/',
    isActive: true
  },
  {
    id: '40',
    organizationName: 'Seattle Office of Arts & Culture',
    website: 'https://www.seattle.gov/arts',
    budgetMin: 1000,
    budgetMax: 25000,
    deadline: '2025-10-28',
    deadlineNotes: 'Arts in Parks: October 28, 2025. CityArtist: varies by discipline. Youth Arts: March 2025. Civic Poet: August 2026.',
    location: 'Seattle, WA',
    artsDiscipline: 'General Arts',
    fundingType: 'Project-Based',
    funderType: 'Government',
    eligibility: 'Seattle-based artists and organizations. Arts in Parks for underserved and economically constrained areas.',
    overview: 'Multiple grant programs for Seattle artists and organizations. Arts in Parks: $1,000-$10,000 for park activations May-October 2026. Civic Poet: $25,000. Creative Advantage roster: up to $12,000.',
    applicationUrl: 'https://www.seattle.gov/arts/programs/grants',
    isActive: true
  },

  // ==================== EMERGENCY/SPECIAL GRANTS ====================
  {
    id: '41',
    organizationName: 'Foundation for Contemporary Arts - Emergency Grants',
    website: 'https://www.foundationforcontemporaryarts.org',
    budgetMin: 500,
    budgetMax: 5000,
    deadline: '',
    deadlineNotes: 'Rolling applications. Apply 8-10 weeks before public presentation (no earlier than 10 weeks). 6-week minimum lead time for response.',
    location: 'New York, NY',
    artsDiscipline: 'Performing Arts',
    fundingType: 'Project-Based',
    funderType: 'Private Foundation',
    eligibility: 'US-based individual visual and performing artists with committed performance/exhibition dates. 3-year wait period after receiving FCA grant.',
    overview: 'Emergency Grants for urgent funding needs. Average 100 applications monthly, 12-21 grants made. Cancellation Funds deadline April 30, 2026 (Jerome Foundation support). Founded by John Cage and Jasper Johns.',
    contactEmail: 'info@foundationforcontemporaryarts.org',
    applicationUrl: 'https://www.foundationforcontemporaryarts.org/grants/emergency-grants/',
    isActive: true
  },
  {
    id: '42',
    organizationName: 'The Awesome Foundation',
    website: 'https://www.awesomefoundation.org',
    budgetMin: 1000,
    budgetMax: 1000,
    deadline: '',
    deadlineNotes: 'Monthly micro-grants. DC Chapter: 15th of each month. Other chapters have varying schedules. Rolling applications.',
    location: 'Various',
    artsDiscipline: 'General Arts',
    fundingType: 'Project-Based',
    funderType: 'Community Foundation',
    eligibility: 'Anyone with an awesome idea - individuals, groups, organizations. Apply to chapter near you or select "Any."',
    overview: '$1,000 monthly micro-grants, no strings attached. Each chapter independently selects projects. Apply to multiple chapters if relevant. Criteria: Is it awesome? Does it benefit community? Will $1,000 make impact?',
    applicationUrl: 'https://www.awesomefoundation.org/en/submissions/new',
    isActive: true
  },

  // ==================== MUSIC EDUCATION ====================
  {
    id: '43',
    organizationName: 'The Presser Foundation',
    website: 'https://presserfoundation.org',
    budgetMin: 2500,
    budgetMax: 50000,
    deadline: '2025-11-15',
    deadlineNotes: 'Advancement of Music deadline November 15, 2025. Special Projects deadline February 1, 2026. Resilience Grants up to $7,500 for orgs under $150K budget.',
    location: 'Philadelphia, PA',
    artsDiscipline: 'Music Education',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'Music performance, presenting, or pre-collegiate education organizations. Geographic focus: within 75 miles of Philadelphia (PA, NJ, DE, MD including Harrisburg).',
    overview: 'One of few private foundations dedicated solely to music education and philanthropy. Advancement of Music grants $2,500-$50,000 for operating support. Special Projects for new organizations (up to 5 years) and resilience grants.',
    contactEmail: 'grants@presserfoundation.org',
    applicationUrl: 'https://presserfoundation.org/advancement-of-music/',
    isActive: true
  },
  {
    id: '44',
    organizationName: 'Jack Kent Cooke Foundation',
    website: 'https://www.jkcf.org',
    budgetMin: 5000,
    budgetMax: 55000,
    deadline: '2025-11-12',
    deadlineNotes: 'College Scholarship: August 20 - November 12, 2025. Young Scholars: February 5 - April 29, 2026. Graduate Scholarship: January 9, 2026.',
    location: 'Lansdowne, VA',
    artsDiscipline: 'Music Education',
    fundingType: 'Fellowship',
    funderType: 'Private Foundation',
    eligibility: 'High-achieving students with financial need. Organizational grants by invitation for high-impact initiatives benefiting students.',
    overview: 'Primarily scholarship programs for talented students from low-income families. College Scholarship up to $55,000. Young Scholars: 5-year pre-college scholarship for middle schoolers. Some organizational grants available.',
    contactEmail: 'grants@jkcf.org',
    applicationUrl: 'https://www.jkcf.org/our-scholarships/',
    isActive: true
  },

  // ==================== ADDITIONAL GRANTS ====================
  {
    id: '45',
    organizationName: 'Dreyfus Foundation',
    website: 'https://www.dreyfus.org',
    budgetMin: 5000,
    budgetMax: 30000,
    deadline: '2026-06-30',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Project-Based',
    funderType: 'Private Foundation',
    eligibility: 'US-based chamber music organizations and ensembles presenting high-quality performances.',
    overview: 'The Dreyfus Foundation supports chamber music performance, education, and audience development. Grants fund concert presentations, educational programs, and initiatives introducing new audiences to chamber music.',
    isActive: true
  },
  {
    id: '46',
    organizationName: 'Paul M. Angell Family Foundation',
    website: 'https://www.pmaffoundation.org',
    budgetMin: 5000,
    budgetMax: 50000,
    deadline: '2026-07-01',
    location: 'Chicago, IL',
    artsDiscipline: 'Classical Music',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'Classical music organizations with strong artistic programs and community engagement.',
    overview: 'The Foundation supports classical music organizations demonstrating artistic excellence, innovative programming, and commitment to expanding access. Both general operating and project grants available.',
    applicationUrl: 'https://www.pmaffoundation.org/apply',
    isActive: true
  },
  {
    id: '47',
    organizationName: 'Bernstein Family Foundation',
    website: 'https://bernsteinfamilyfoundation.org',
    budgetMin: 5000,
    budgetMax: 25000,
    deadline: '2026-05-01',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Project-Based',
    funderType: 'Private Foundation',
    eligibility: 'Organizations honoring Leonard Bernstein legacy through education, performance, or artistry.',
    overview: 'The Foundation supports programs embodying Leonard Bernstein legacy of artistic excellence, education, and social impact. Priority for music education reaching underserved communities and projects celebrating music-making.',
    isActive: true
  },
  {
    id: '48',
    organizationName: 'Harman Family Foundation',
    website: 'https://harmanfamilyfoundation.org',
    budgetMin: 10000,
    budgetMax: 100000,
    deadline: '2026-06-01',
    location: 'Washington, DC',
    artsDiscipline: 'Performing Arts',
    fundingType: 'General Operating',
    funderType: 'Private Foundation',
    eligibility: 'Performing arts organizations in the Washington, DC area with strong artistic programming.',
    overview: 'The Harman Family Foundation supports performing arts organizations demonstrating artistic excellence and serving diverse audiences. Multi-year general operating grants available for established organizations.',
    isActive: true
  },
  {
    id: '49',
    organizationName: 'Capitol Hill Community Foundation',
    website: 'https://www.capitolhillcommunityfoundation.org',
    budgetMin: 1000,
    budgetMax: 10000,
    deadline: '2026-05-15',
    location: 'Washington, DC',
    artsDiscipline: 'General Arts',
    fundingType: 'Project-Based',
    funderType: 'Community Foundation',
    eligibility: 'Organizations and projects serving the Capitol Hill neighborhood of Washington, DC.',
    overview: 'CHCF supports community-based arts programming enhancing quality of life on Capitol Hill. Grants fund concerts, performances, arts education, and cultural events bringing neighbors together.',
    applicationUrl: 'https://www.capitolhillcommunityfoundation.org/grants',
    isActive: true
  },
  {
    id: '50',
    organizationName: 'American Composers Orchestra - Underwood Commission',
    website: 'https://www.americancomposers.org',
    budgetMin: 15000,
    budgetMax: 25000,
    deadline: '2026-06-15',
    location: 'New York, NY',
    artsDiscipline: 'Classical Music',
    fundingType: 'Commissioning',
    funderType: 'Service Organization',
    eligibility: 'American composers of orchestral music. Emerging and established composers eligible.',
    overview: 'ACO commissions and performs new orchestral works by American composers. The Underwood Commission supports composers creating innovative orchestral works with guaranteed premiere performances.',
    applicationUrl: 'https://www.americancomposers.org/commissions',
    isActive: true
  }
];

export const artsDisciplines = ['Classical Music', 'General Arts', 'Humanities', 'Performing Arts', 'Music Education'];
export const fundingTypes = ['General Operating', 'Project-Based', 'Capital', 'Fellowship', 'Commissioning'];
export const funderTypes = ['Government', 'Private Foundation', 'Corporate', 'Community Foundation', 'Service Organization'];
export const locations = [
  'Washington, DC', 'New York, NY', 'Boston, MA', 'Philadelphia, PA', 'Richmond, VA',
  'Baltimore, MD', 'Saint Paul, MN', 'Miami, FL', 'Chicago, IL', 'Los Angeles, CA',
  'San Francisco, CA', 'Seattle, WA', 'Atlanta, GA', 'Detroit, MI', 'Minneapolis, MN',
  'Santa Barbara, CA', 'Indianapolis, IN', 'New Orleans, LA', 'Troy, MI', 'Various',
  'Sacramento, CA', 'Harrisburg, PA', 'Provo, UT', 'Cambridge, MA', 'Lenox, MA',
  'Aspen, CO', 'North Adams, MA', 'Santa Monica, CA', 'Lansdowne, VA'
];
